# Generated by Django 5.2.8 on 2026-05-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
